vault_borgmatic_ssh_private_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
  QyNTUxOQAAACB7JKGbl6IEwWZAceCiZ96vphRozsHpCNGwHgX9eqO+LAAAAJiurYHcrq2B
  3AAAAAtzc2gtZWQyNTUxOQAAACB7JKGbl6IEwWZAceCiZ96vphRozsHpCNGwHgX9eqO+LA
  AAAEBd2TEwu8faPCMNyjDgpPoKaKMulAFFXy4xa4auEnfHV3skoZuXogTBZkBx4KJn3q+m
  FGjOwekI0bAeBf16o74sAAAADmJvcmdtYXRpY0B2cHMyAQIDBAUGBw==
  -----END OPENSSH PRIVATE KEY-----
vault_wireguard_private_key: QC1gRolQJ4PLtd8+WBahSTbA9Ca/7tagr7QP0dXjLnk=

