---
- name: Borg destination
  become: true
  block:
    - name: Create user borg
      ansible.builtin.user:
        name: borg
        home: /srv/borg

    - name: Install borg packages
      ansible.builtin.apt:
        pkg:
          - borgbackup

