---
- name: Grafana, Loki and Alloy as root
  become: true
  block:

    - name: Enable Grafana repo via extrepo
      ansible.builtin.command:
        cmd: extrepo enable grafana
        creates: /etc/apt/sources.list.d/extrepo_grafana.sources

    - name: Install grafana, loki and alloy
      ansible.builtin.apt:
        pkg:
          - grafana
          - loki
          - alloy
        update_cache: true

    # Grafana

    - name: Instanciate grafana config
      ansible.builtin.template:
        src: grafana.ini.j2
        dest: /etc/grafana/grafana.ini
        mode: u=rw,g=r
      notify: grafana changed

    - name: Copy grafana dashboards
      ansible.builtin.copy:
        src: grafana/dashboards/
        dest: /var/lib/grafana/dashboards/
        owner: root
        group: grafana
        mode: u=rw,g=r
      notify: grafana changed

    - name: Copy grafana provisioning files
      ansible.builtin.copy:
        src: grafana/provisioning/
        dest: /etc/grafana/provisioning/
        owner: root
        group: grafana
        mode: u=rw,g=r
        directory_mode: u=rwx,g=rx,o=rx
      notify: grafana changed

    - name: Make grafana-server systemd override directory
      ansible.builtin.file:
        path: /etc/systemd/system/grafana-server.service.d
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Cap grafana-server memory usage
      ansible.builtin.copy:
        src: grafana-server-memory.conf
        dest: /etc/systemd/system/grafana-server.service.d/memory.conf
        mode: u=rw,g=r,o=r
      notify:
        - systemd changed
        - grafana changed

    - name: Force handlers to run immediately
      ansible.builtin.meta: flush_handlers

    - name: Start grafana
      ansible.builtin.systemd:
        name: grafana-server
        enabled: true
        state: started

    # Loki

    - name: Make /var/lib/loki directory
      ansible.builtin.file:
        path: /var/lib/loki
        state: directory
        owner: loki
        mode: u=rwx,g=,o=

    - name: Instanciate loki config
      ansible.builtin.copy:
        src: loki-config.yml
        dest: /etc/loki/config.yml
        mode: u=rw,g=r,o=r
      notify: loki changed

    - name: Start loki
      ansible.builtin.systemd:
        name: loki
        enabled: true
        state: started

    # Alloy

    - name: Instanciate alloy config
      ansible.builtin.copy:
        src: alloy-config.alloy
        dest: /etc/alloy/config.alloy
        mode: u=rw,g=r,o=r
      notify: alloy changed

    - name: Start alloy
      ansible.builtin.systemd:
        name: alloy
        enabled: true
        state: started

    # Caddy

    - name: Register grafana caddy file
      ansible.builtin.copy:
        src: grafana.caddy
        dest: /etc/caddy/sites.d/grafana.caddy
        mode: u=rw,g=r,o=r
      notify: caddy changed
