---
- name: "Generate workstation wireguard config"
  hosts: workstations
  connection: local
  vars:
    group_suffix: "-workstation"
  roles:
    - role: wireguard
      tags:
        - wireguard
        - workstation
  tags:
    - never

- name: "Initial ssh configuration"
  hosts: servers
  roles:
    - role: authorized_keys
      tags: ["authorized_keys"]
    - role: sshd
      tags: ["sshd"]
  tags:
    - ssh

- name: "Setup common facts for all machines in the inventory"
  hosts: servers
  vars:
    group_suffix: "-server"
  roles:
    - role: common_facts
      tags: ["common_facts"]
    - role: common_packages
      tags: ["common_packages"]
    - role: hostname
      tags: ["hostname"]
    - role: timezone
      tags: ["timezone"]
    - role: upgrade
      tags: ["upgrade"]
    - role: ufw
      tags: ["ufw"]
    - role: wireguard
      tags: ["wireguard"]
    - role: srv
      tags: ["srv"]
  tags:
    - common

- name: Setup webservers
  hosts: webservers
  roles:
    - role: systemd_handlers
    - role: caddy_handlers
    - role: caddy
      tags: ["caddy"]
  tags:
    - webservers

- name: Setup borg repository stores
  hosts: backup_destinations
  roles:
    - borg_destination
  tags:
    - backup
    - destination

- name: Setup borg no servers that needs to be backed up
  hosts: backup_sources
  roles:
    - systemd_handlers
    - borgmatic
    - role: borgmatic_system
      tags: ["borgmatic_system"]
  tags:
    - backup
    - source

- name: Setup vouchers
  hosts: vouchers
  roles:
    - role: systemd_handlers
    - role: caddy_handlers
    - role: vouchers
  tags:
    - vouchers

# Everything below is the old setup being migrated
# ---
# - name: "Setup Wireguard"
#   hosts: all
#   become: true
#   roles:
#     - systemd
#     - wireguard
#
#
# - name: "Setup hosts to backup"
#   hosts: backuphead
#   become: true
#   roles:
#     - systemd
#     - borgbackup
#
# - name: Setup dataproxies
#   hosts: dataproxies
#   become: true
#   roles:
#     - systemd
#     - gdrivesync
#
# - name: Setup influxdb
#   hosts: webservers
#   become: true
#   roles:
#     - influxdata-common
#     - influxdata-influxdb
#
# - name: Setup telegraf
#   hosts: servers
#   become: true
#   roles:
#     - influxdata-common
#     - influxdata-telegraf
#
# - name: "Setup web applications"
#   hosts: webservers
#   become: true
#   roles:
#     - systemd
#     - nginx
#     - nginx-membres
#     - nginx-vouchers
#     - grafana
#     - wordpress
#
# - name: Setup kiosks
#   hosts: kiosks
#   roles:
#     - kiosk
#
# - name: Setup vouchers
#   hosts: vouchers
#   become: true
#   roles:
#     - systemd
#     - vouchers
