---
- name: "Generate workstation wireguard config"
  hosts: workstations
  connection: local
  vars:
    group_suffix: "-workstation"
  roles:
    - role: wireguard
      tags:
        - wireguard
        - workstation
  tags:
    - never

- name: "Setup common facts for all machines in the inventory"
  hosts: servers
  roles:
    - role: common_facts
      tags: ["common_facts"]
    - role: authorized_keys
      tags: ["authorized_keys"]
    - role: common_packages
      tags: ["common_packages"]
    - role: hostname
      tags: ["hostname"]
    - role: timezone
      tags: ["timezone"]
    - role: upgrade
      tags: ["upgrade"]
    - role: ufw
      tags: ["ufw"]
  tags:
    - common

- name: Setup webservers
  hosts: webservers
  roles:
    - role: caddy
      tags: ["caddy"]

# Everything below is the old setup being migrated
# ---
# - name: "Setup Wireguard"
#   hosts: all
#   become: true
#   roles:
#     - systemd
#     - wireguard
#
# - name: Setup borg repository stores
#   hosts: borgstores
#   become: true
#   roles:
#     - borgstore
#
# - name: "Setup hosts to backup"
#   hosts: backuphead
#   become: true
#   roles:
#     - systemd
#     - borgbackup
#
# - name: Setup dataproxies
#   hosts: dataproxies
#   become: true
#   roles:
#     - systemd
#     - gdrivesync
#
# - name: Setup influxdb
#   hosts: webservers
#   become: true
#   roles:
#     - influxdata-common
#     - influxdata-influxdb
#
# - name: Setup telegraf
#   hosts: servers
#   become: true
#   roles:
#     - influxdata-common
#     - influxdata-telegraf
#
# - name: "Setup web applications"
#   hosts: webservers
#   become: true
#   roles:
#     - systemd
#     - nginx
#     - nginx-membres
#     - nginx-vouchers
#     - grafana
#     - wordpress
#
# - name: Setup kiosks
#   hosts: kiosks
#   roles:
#     - kiosk
#
# - name: Setup vouchers
#   hosts: vouchers
#   become: true
#   roles:
#     - systemd
#     - vouchers
