[project]
name = "ansible-automation"
version = "0.0.1"
description = "Épicerie le Détour Ansible playbook"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible",
    "ansible-core",
    "ansible-lint",
    "libvirt-python",
    "molecule",
    "molecule-libvirt-ng",
]

[tool.uv]
# Optional: Ensures uv syncs your environment exactly to a lockfile
managed = true
