servers:
  hosts:
#    pi1:
    srv1:
    vps2:

backup_destinations:
  hosts:
#    pi1:
    srv1:

backup_sources:
  hosts:
    vps2:

webservers:
  hosts:
    vps2:

vouchers:
  hosts:
    vps2:

grafana:
  hosts:
    srv1:

