workstations:
  hosts:
    charles-ws:

servers:
  hosts:
    vps2:
      ansible_host: vps-53fcb87d.vps.ovh.ca
      ansible_user: debian
    pi1:
      ansible_host: 192.168.211.90
      ansible_user: debian

