---
- name: Caddy
  become: true
  block:
    - name: Enable Caddy repo via extrepo
      ansible.builtin.command:
        cmd: extrepo enable caddyserver
        creates: /etc/apt/sources.list.d/extrepo_caddyserver.sources

    - name: Update apt cache after enabling new repo
      ansible.builtin.apt:
        update_cache: true

    - name: Install caddy
      ansible.builtin.apt:
        name: caddy
        state: present

    - name: Open http port 80 for caddy
      community.general.ufw:
        rule: allow
        port: http

    - name: Open https port 443 for caddy
      community.general.ufw:
        rule: allow
        port: https

