- name: Install git
  apt:
    pkg:
      - git
  tags:
    - nginx-membres

- name: Git checkout membres.epicerieledetour.org
  git:
    repo: 'https://github.com/epicerieledetour/ledetour-membres.git'
    dest: /var/www/ledetour-membres
    version: dev/private
  tags:
    - nginx-membres

- include_tasks:
    file: "main{{ deployment_suffix }}.yml"
  tags:
    - nginx-membres

- set_fact:
    membres_ssl_clients_snippet_conf: ledetour-membres-ssl-clients.conf
  tags:
    - nginx-membres

- name: Link membres.epicerieledetour.org ssl clients nginx snippet
  ansible.builtin.file:
    src: "/var/www/ledetour-membres/nginx/{{ membres_ssl_clients_snippet_conf }}"
    dest: "/etc/nginx/snippets/{{ membres_ssl_clients_snippet_conf }}"
    state: link
  notify:
    - systemd changed
  tags:
    - nginx-membres

- name: Instanciate membres nginx config
  template:
    src: membres.conf.j2
    dest: /etc/nginx/sites-available/membres.conf
    mode: u=r,g=r,o=r
  notify:
    - nginx changed
  tags:
    - nginx-membres

- name: Enable membres.epicerieledetour.org nginx configuration file
  file:
    src: /etc/nginx/sites-available/membres.conf
    dest: /etc/nginx/sites-enabled/membres.conf
    state: link
  tags:
    - nginx-membres

- name: Create /etc/ledetour-membres
  ansible.builtin.file:
    path: /etc/ledetour-membres
    state: directory
  tags:
    - nginx-membres

- name: Create /var/run/ledetour-membres
  ansible.builtin.file:
    path: /var/run/ledetour-membres
    state: directory
    mode: u=rwx,g=rx,o=rx
  tags:
    - nginx-membres

- name: Instanciate membres.epicerieledetour.org database update systemd env file
  ansible.builtin.template:
    src: ledetour-membres.env.j2
    dest: /etc/ledetour-membres/ledetour-membres.env
    mode: u=r,g=,o=
  tags:
    - nginx-membres

- name: Copying membres.epicerieledetour.org database update systemd service file
  ansible.builtin.file:
    src: /var/www/ledetour-membres/systemd/update-ledetour-membres-data.service
    dest: /etc/systemd/system/update-ledetour-membres-data.service
    state: link
  notify:
    - systemd changed
  tags:
    - nginx-membres

- name: Copying membres.epicerieledetour.org membres.json update systemd timer file
  ansible.builtin.file:
    src: /var/www/ledetour-membres/systemd/update-ledetour-membres-data.timer
    dest: /etc/systemd/system/update-ledetour-membres-data.timer
    state: link
  notify:
    - systemd changed
  tags:
    - nginx-membres

- name: Enable membres.epicerieledetour.org membres.json update systemd timer
  systemd:
    name: update-ledetour-membres-data.timer
    state: started
    enabled: yes
  tags:
    - nginx-membres
