---
- name: Vouchers
  become: true
  block:

  # Dependencies
  
  - name: Enable extrepo policies
    ansible.builtin.lineinfile:
      path: /etc/extrepo/config.yaml
      regexp: "# - {{ item }}"
      line: "- {{ item }}"
    loop:
      - contrib
      - non-free

  - name: Enable extrepo source uv
    ansible.builtin.command: "extrepo enable uv"
    args:
      creates: "/etc/apt/sources.list.d/extrepo_uv.sources"

  - name: Install vouchers dependencies
    ansible.builtin.apt:
      pkg:
        - git
        - libcairo2
        - sqlite3
        - uv
      update_cache: true

  # Run folder

  - name: Make vouchers.epicerieledetour.org installation folder hierarchy
    ansible.builtin.file:
      path: "/srv/www/vouchers.epicerieledetour.org/files/emissions/{{ ldtvouchers_hack_emissiontoken }}"
      state: directory
      mode: "0755"
      owner: "www-data"
      group: "www-data"

  # systemd: report

  - name: Instanciate vouchers.epicerieledetour.org ldt-vouchers-report.service
    ansible.builtin.template:
      src: ldt-vouchers-report.service.j2
      dest: /etc/systemd/system/ldt-vouchers-report.service
      mode: u=r,g=r,o=
    notify:
      - vouchers changed

  - name: Copying vouchers.epicerieledetour.org report timer file
    ansible.builtin.copy:
      src: ldt-vouchers-report.timer
      dest: /etc/systemd/system/
    notify:
      - vouchers changed


  # systemd: service

  - name: Copying vouchers.epicerieledetour.org systemd service file
    ansible.builtin.copy:
      src: ldt-vouchers.service
      dest: /etc/systemd/system/
    notify:
      - vouchers changed


 # caddy

  - name: Register vouchers caddy file
    ansible.builtin.copy:
      src: vouchers.caddy
      dest: /etc/caddy/sites.d/vouchers.caddy
    notify:
      - caddy changed

  - name: Setup backup
    ansible.builtin.include_tasks:
      file: backup.yml

