{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ufw",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ufw\"}"
    }
   ]
  },
  {
   "title": "fail2ban",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"fail2ban\"}"
    }
   ]
  },
  {
   "title": "auth",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"ssh\"}"
    }
   ]
  }
 ]
}