---
- name: Ufw
  become: true
  block:
    - name: Install ufw
      ansible.builtin.apt:
        pkg:
          - rsyslog  # ufw logging to /var/log/ufw.log needs it
          - ufw

    - name: Disable all ports but ssh
      community.general.ufw:
        state: enabled
        policy: deny
        rule: allow
        port: 22
