---
dependency:
  name: galaxy
#  options:
#    requirements-file: requirements.yml

driver:
  name: libvirt

#    image_url: "https://cloud.debian.org/images/cloud/trixie/current/debian-13-genericcloud-amd64.qcow2"


platforms:
  - name: vps2
    image_url: "https://saimei.ftp.acc.umu.se/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2"
    memory_size: 1 # GB
    vcpu: 1
    disk_size: "5G"
    qemu_user: "libvirt-qemu"
  - name: srv1
    image_url: "https://saimei.ftp.acc.umu.se/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2"
    memory_size: 1 # GB
    vcpu: 1
    disk_size: "5G"
    qemu_user: "libvirt-qemu"

provisioner:
  name: ansible
  config_options:
    defaults:
#      vault_password_file: ../../vault_password.sh
      vault_password_file: "${MOLECULE_PROJECT_DIRECTORY}/vault_password.sh"
  inventory:
    links:
      hosts: ../../hosts-dev

