borgmatic_etc_dir: "/etc/borgmatic.d"
borgmatic_snippets_dir: "{{ borgmatic_etc_dir }}/snippets"
borgmatic_snippets_common: "{{ borgmatic_snippets_dir }}/common.yaml"
borgmatic_ssh_dir: "{{ borgmatic_etc_dir }}/ssh"
borgmatic_ssh_id: "{{ borgmatic_ssh_dir }}/id"

