---
borg_passphrase: "{{ vault_borg_passphrase }}"
ssh_host_private_ed25519_key: "{{ vault_ssh_host_private_ed25519_key }}"
ssh_host_public_ed25519_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAbyaB9DI9OzpKQwOLPP/9lFdc5kbMYLMrhpEx9mG63h root@srv1"
wireguard_type: client
wireguard_address: 192.168.211.60
wireguard_private_key: "{{ vault_wireguard_private_key }}"
wireguard_public_key: "uy1DHEWISIb5mIQm/0KlV20TfTyrh2BIRCYV/dNG1GQ="
wireguard_endpoint_port: 51820
