---
- name: Prometheus
  become: true
  block:

    - name: Install prometheus
      ansible.builtin.apt:
        pkg:
          - prometheus

    - name: Instanciate prometheus config
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        mode: u=rw,g=r,o=r
      notify: prometheus changed

    - name: Start prometheus
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: started
