---
- name: Install influxdb
  ansible.builtin.apt:
    pkg:
      - influxdb

- name: Open port 8086 for influxdb on wireguard network
  community.general.ufw:
    rule: allow
    port: "8086"
    from_ip: 192.168.211.0/24

- name: Start InfluxDB
  ansible.builtin.systemd:
    name: influxdb
    enabled: true
    state: started
